name: docker-n-doc-build
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build-n-deploy:
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker Hub
        if: ${{ steps.extract_branch.outputs.branch == 'master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Deploy Production images
        #env:
        #  DOCKER_IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
        if: ${{ steps.extract_branch.outputs.branch == 'master' }}
        run: |
          docker-compose build eluna-ts-build
          docker-compose  push eluna-ts-build
