name: Eluna TS Definitions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm lint
  deploy:
      needs: checks
    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
      npm install
      npm publish
