name: Eluna TS Definitions

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - deps/eluna-ts-definitions/**
  pull_request:
    branches: [ master ]
    paths:
      - deps/eluna-ts-definitions/**

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd deps/eluna-ts-definitions
        npm install
        npm run lint
  deploy:
    needs: checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - name: Update version in package.json
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGEJSON_DIR: deps/eluna-ts-definitions
      with:
        tag-prefix:  'definitions-'
    - name: Publish package
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: deps/eluna-ts-definitions/package.json
